In [1]:
import pandas as pd


date_range=pd.date_range(start="20180801",periods=4)
df=pd.DataFrame({'book':[12,13,15,22],
'box':[3,8,13,18],
'pen':[5,7,12,15]},index=date_range)

df

            book  box  pen
2018-08-01    12    3    5
2018-08-02    13    8    7
2018-08-03    15   13   12
2018-08-04    22   18   15

In [4]:
df.to_csv('2班bbp2.csv',index_label='timestamp')

In [5]:
value = pd.read_table('../1.txt')
value

  C  Python Java
0    1  4      5
1    3  3      4
2    4  2      3
3    2  1      1

In [6]:
# 正则表达式
value = pd.read_table('../1.txt',sep='\s+',engine='python')
value

   C  Python  Java
0  1       4     5
1  3       3     4
2  4       2     3
3  2       1     1

In [7]:
value = pd.read_excel('chengji.xlsx')
value

     Student ID   name   C  database  oracle  Java
0  541513440106   ding  77        80      95    91
1  541513440242    yan  83        90      93    90
2  541513440107   feng  85        90      92    91
3  541513440230   wang  86        80      86    91
4  541513440153  zhang  76        90      90    92
5  541513440235     lu  69        90      83    92
6  541513440224    men  79        90      86    90
7  541513440236    fei  73        80      85    89
8  541513440210    han  80        80      93    88